# Generated by Django 6.0.2 on 2026-02-09 20:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='distribuidor',
            new_name='supplier',
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('company', 'slug'), name='unique_product_slug_per_company'),
        ),
    ]
