# Generated by Django 5.1.5 on 2026-02-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_add_batch_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(fields=('product', 'code'), name='unique_batch_code_per_product'),
        ),
    ]
